require 'my_docker_rake/tasks'

MyDockerRake::Tasks.new do |c|
  c.containers = [
    {
      name:  'mydockerrake.data',
      image: 'mydockerrake/data',
      protect_deletion: true,
    },
    {
      name:  'mydockerrake.sshd',
      image: 'mydockerrake/sshd:v2',
      volumes_from: ['mydockerrake.data'],
      ports: [22]
    },
  ]
end
